Repository Strategy11/formidable-modal, pull requests merged in 2023-06, with the labels that each got.

#16 Shortcode block
  .editorconfig
  .github/workflows/phpcs.yml
  .github/workflows/phpunit.yml
  .github/workflows/qadelete.yml
  .github/workflows/qadeploy.yml
  .gitignore
  blocks-src/frm-modal-button/block.json
  blocks-src/frm-modal-button/edit.js
  blocks-src/frm-modal-button/editor.scss
  blocks-src/frm-modal-button/index.js
  blocks-src/frm-modal-button/save.js
  blocks-src/frm-modal-button/style.scss
  blocks-src/frm-modal-content/block.json
  blocks-src/frm-modal-content/edit.js
  blocks-src/frm-modal-content/editor.scss
  blocks-src/frm-modal-content/helpers.js
  blocks-src/frm-modal-content/index.js
  blocks-src/frm-modal-content/save.js
  blocks-src/frm-modal/block.json
  blocks-src/frm-modal/edit.js
  blocks-src/frm-modal/index.css
  blocks-src/frm-modal/index.js
  blocks-src/index.js
  blocks/frm-modal-button/block.json
  blocks/frm-modal-button/index.asset.php
  blocks/frm-modal-button/index.js
  blocks/frm-modal-content/block.json
  blocks/frm-modal-content/index.asset.php
  blocks/frm-modal-content/index.css
  blocks/frm-modal-content/index.js
  blocks/frm-modal/block.json
  blocks/frm-modal/index.asset.php
  blocks/frm-modal/index.js
  classes/frmBtsModApp.php
  classes/frmBtsModBlockController.php
  classes/frmBtsModUpdate.php
  css/bootstrap-modal.css
  css/bootstrap.css
  css/bootstrap.min.php
  formidable-modal.php
  js/bootstrap-modal.min.js
  js/bootstrap.min.js
  package-lock.json
  package.json
  phpcs.xml
  phpunit.xml
  readme.txt
  tests/bootstrap.php
  tests/test_FrmBtsModDirectFileAccess.php
  tests/test_frmBtsModApp.php
  tests/test_frmBtsModBlockController.php
Labels: beta deploy, run analysis, needs qa

#20 Prepare for 3.0
  blocks/frm-modal-content/index.asset.php
  blocks/frm-modal-content/index.css
  classes/frmBtsModApp.php
  languages/formidable-modal.pot
  package-lock.json
  package.json
  readme.txt
Labels: run analysis

#23 Fix conflict with Bootstrap 3
  css/bootstrap-modal.css
Labels: needs qa
